---
title: "Building this website"
description: |
  A new online business card of sorts
date: 02-18-2021
categories:
  - Design
  - Networking
output:
  distill::distill_article:
    self_contained: false
---

## *Content*

As I enter the final years of graduate school, I decided to build a website as a professional landing page. `blogdown` was a likely candidate, but ended up deciding on `distill` due to similar functionality and an opinionated framework I enjoyed. Despite less design flexibility, I was still able to tweak it a bit to a preferred dark theme.

I've written semi-frequently in the past for [Massive Science](https://massivesci.com/people/joshua-peters/) and hope to continue some personal musings here. I imagine it will move away from public interest and towards emerging biotechnology: startups, venture capital, etc.

## Resources and Inspo

<i class="fas fa-check"></i> Alison Hill's [tutorial](https://alison.rbind.io/post/2020-12-22-postcards-distill/) on using `postcards` with `distill`.

<i class="fas fa-check"></i> Thomas Mock's [tutorial](https://themockup.blog/posts/2020-08-01-building-a-blog-with-distill/).

<i class="far fa-thumbs-up"></i> Maggie Appleton's [website](https://maggieappleton.com/). Beautiful color scheme and typography. Unique copy. Calming simplicity.  

<i class="far fa-thumbs-up"></i> Alison Hill's [website](https://alison.rbind.io/). Academic information with typical pages. Biography-based landing page. Great color scheme. Relevant content.
